inference:
  batch_size: 1
  colormap_type: jet
  num_workers: 1
  save_colormap: true
input:
  height: 1024
  width: 2048
load_weights_dir: /mnt/projects/roadside_vision/models/DAP-weights
median_align: false
model:
  args:
    fine_tune_type: hypersim
    max_depth: 1.0
    midas_model_type: vitl
    min_depth: 0.01
    train_decoder: true
  name: dap
